spring:
  data:
    redis:
      host: redis-17424.c54.ap-northeast-1-2.ec2.cloud.redislabs.com
      port: 17424
      username: default
      password: IfmiRKmPXtn3b5C7KCAi6ZgopnUuSgAF

  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always